# SPDX-License-Identifier: MIT

name: Crowdin Download

# TODO: codeowners
# TODO: schedule?

on:
  workflow_dispatch:

permissions:
  read-all

# https://github.com/crowdin/github-action/wiki/Handling-parallel-runs
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  download:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write

    steps:
    - uses: actions/checkout@v3

    - name: Download from Crowdin
      uses: crowdin/github-action@v1.6.0
      with:
        config: crowdin.yml
        upload_sources: false
        download_translations: true
        download_translations_args: --all
        create_pull_request: true
        localization_branch_name: ci/docs/crowdin-auto-download
        pull_request_labels: "s: needs review, skip news, t: localization"
      env:
        API_KEY: ${{ secrets.CROWDIN_API_KEY }}
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        INPUT_DEBUG_MODE: true
